backend:
  name: git-gateway
  repo: shrey2005/NextjsWithNetlify
  branch: main
media_folder: assets/Images
public_folder: Images
collections:
  - name: "profile"
    label: "Profile"
    files:
      - label: "Profile Home"
        name: "profile"
        file: "content/MyProfile.md"
        fields:
          - { label: "Name", name: "username", widget: "string" }
          - { label: "Company", name: "company", widget: "string" }
          - { label: "Developer", name: "devloper", widget: "string" }
          - { label: "Designation", name: "designation", widget: "string" }
          - { label: "Image", name: "thumbnail", widget: "image" }
          - label: "Address"
            name: "address"
            widget: object
            fields:
              - { label: "StreetNo", name: "streetNo", widget: "string" }
              - { label: "Apartment", name: "apartment", widget: "string" }
              - { label: "Area", name: "area", widget: "string" }
              - { label: "City", name: "city", widget: "string" }
              - { label: "State", name: "state", widget: "string" }

